SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `tekkit`.`ControllerBlock_Lord` 
DROP INDEX `LOCATION` 
, ADD UNIQUE INDEX `LOCATION` (`x` ASC, `y` ASC, `z` ASC, `world` ASC) ;

ALTER TABLE `tekkit`.`ControllerBlock_Serf` 
COMMENT = 'Controlled blocks.\n\nTo add: Inventory, other data' ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
