name: ControllerBlock4K
description: Toggle blocks on and off with redstone
author: Hell_Fire
authors: [Zero9195, Sorklin, Techzune, astronouth7303]
main: me.operon.controllerblockwe.ControllerBlock
version: 2
database: true
commands:
    cblock:
        description: Reload the config.
