name: ControllerBlock4K
description: Toggle blocks on and off with redstone
author: Hell_Fire
authors: [Zero9195, Sorklin, Techzune, astronouth7303]
main: com.astro73.controllerblock4k.ControllerBlock
version: 1
database: true
depend: [WorldEdit]
commands:
    cblock:
        description: Entry point to ControllerBlock, see /cblock help.
